#!/usr/bin/env bash
# Generate docs/DATABASE.generated.md (tables, columns, enums, views, functions, triggers, policies)
# from a database that already has the migration applied.
#   scripts/db-doc.sh [db_name]     (default: erp_doc — it is (re)created and migrated first)
set -euo pipefail
DB_NAME="${1:-erp_doc}"
CONTAINER="${PG_CONTAINER:-erp-pg}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/docs/DATABASE.generated.md"

if [ "$DB_NAME" != "postgres" ]; then
  SKIP_SEED=1 SKIP_TESTS=1 bash "$ROOT/scripts/db-test.sh" "$DB_NAME" >/dev/null
fi

q() { docker exec -i -e PGPASSWORD=postgres "$CONTAINER" psql -U postgres -h 127.0.0.1 -d "$DB_NAME" -v ON_ERROR_STOP=1 -X -q -A -t "$@"; }

{
  echo "# Database reference (generated)"
  echo
  echo "Generated by scripts/db-doc.sh from the applied migration. Do not edit by hand — see docs/DATABASE.md for semantics."
  echo
  echo "## Enums"
  echo
  q <<'SQL'
select '- `' || t.typname || '`: ' || string_agg('`' || e.enumlabel || '`', ', ' order by e.enumsortorder)
from pg_type t join pg_enum e on e.enumtypid = t.oid join pg_namespace n on n.oid = t.typnamespace
where n.nspname = 'public' group by t.typname order by t.typname;
SQL
  echo
  echo "## Tables"
  echo
  for tbl in $(q -c "select table_name from information_schema.tables where table_schema='public' and table_type='BASE TABLE' order by table_name"); do
    echo "### \`$tbl\`"
    desc=$(q -c "select coalesce(obj_description('public.$tbl'::regclass, 'pg_class'), '')")
    [ -n "$desc" ] && echo "$desc" && echo
    echo "| column | type | null | default | note |"
    echo "|---|---|---|---|---|"
    q -v tbl="$tbl" <<'SQL'
select '| `' || c.column_name || '` | ' ||
  case when c.data_type = 'USER-DEFINED' then c.udt_name
       when c.data_type = 'numeric' and c.numeric_precision is not null then 'numeric(' || c.numeric_precision || ',' || c.numeric_scale || ')'
       when c.data_type = 'ARRAY' then c.udt_name
       else c.data_type end || ' | ' ||
  case when c.is_nullable = 'YES' then 'yes' else 'no' end || ' | ' ||
  coalesce(replace(c.column_default, '|', '\|'), '') || ' | ' ||
  coalesce(case when c.is_generated = 'ALWAYS' then 'GENERATED: ' || replace(c.generation_expression, '|', '\|') || ' ' else '' end, '') ||
  coalesce(col_description(('public.' || c.table_name)::regclass, c.ordinal_position), '') || ' |'
from information_schema.columns c
where c.table_schema = 'public' and c.table_name = :'tbl' order by c.ordinal_position;
SQL
    cons=$(q -v tbl="$tbl" <<'SQL'
select '- ' || conname || ': ' || pg_get_constraintdef(oid) from pg_constraint
where conrelid = ('public.' || :'tbl')::regclass and contype in ('p','u','f','c') order by contype, conname;
SQL
)
    if [ -n "$cons" ]; then echo; echo "Constraints:"; echo "$cons"; fi
    idx=$(q -c "select '- ' || indexdef from pg_indexes where schemaname='public' and tablename='$tbl' and indexname not like '%_pkey' order by indexname")
    if [ -n "$idx" ]; then echo; echo "Indexes:"; echo "$idx"; fi
    trg=$(q -v tbl="$tbl" <<'SQL'
select '- ' || tgname || ': ' || pg_get_triggerdef(t.oid) from pg_trigger t
where tgrelid = ('public.' || :'tbl')::regclass and not tgisinternal order by tgname;
SQL
)
    if [ -n "$trg" ]; then echo; echo "Triggers:"; echo "$trg"; fi
    pol=$(q -c "select '- ' || policyname || ' (' || cmd || ', roles=' || array_to_string(roles, ',') || ')' from pg_policies where schemaname='public' and tablename='$tbl' order by policyname")
    rls=$(q -c "select relrowsecurity from pg_class where oid='public.$tbl'::regclass")
    echo; echo "RLS enabled: $rls"; [ -n "$pol" ] && echo "$pol"
    echo
  done
  echo "## Views"
  echo
  for v in $(q -c "select table_name from information_schema.views where table_schema='public' order by table_name"); do
    echo "### \`$v\`"
    echo "| column | type |"
    echo "|---|---|"
    q -v v="$v" <<'SQL'
select '| `' || column_name || '` | ' || case when data_type='USER-DEFINED' then udt_name else data_type end || ' |' from information_schema.columns where table_schema='public' and table_name = :'v' order by ordinal_position;
SQL
    echo
  done
  echo "## Functions (RPC & triggers)"
  echo
  q <<'SQL'
select '- `' || p.proname || '(' || pg_get_function_arguments(p.oid) || ')` → `' || pg_get_function_result(p.oid) || '`' ||
  case when p.prosecdef then ' SECURITY DEFINER' else '' end ||
  coalesce(' — ' || obj_description(p.oid, 'pg_proc'), '')
from pg_proc p join pg_namespace n on n.oid = p.pronamespace
where n.nspname = 'public' and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e') order by p.proname;
SQL
  echo
  echo "## Grants on functions (anon / authenticated)"
  echo
  q <<'SQL'
select '- `' || p.proname || '`: anon=' || has_function_privilege('anon', p.oid, 'execute') || ', authenticated=' || has_function_privilege('authenticated', p.oid, 'execute')
from pg_proc p join pg_namespace n on n.oid = p.pronamespace
where n.nspname = 'public' and p.proname not like 'trg_%' and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e') order by p.proname;
SQL
} > "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
