import type { InvoiceParsedData } from "@/types/restaurant";

/**
 * Hóa đơn mẫu (Demo Invoices) thực tế giúp người dùng kiểm thử ngay lập tức.
 */
export const SAMPLE_DEMO_INVOICES: Array<{
  id: string;
  name: string;
  description: string;
  supplierName: string;
  data: InvoiceParsedData;
}> = [
  {
    id: "rau-cu-qua-da-lat",
    name: "Hóa đơn Nông Sản & Rau Củ Tươi (Có & Không Thuế)",
    description: "Nhà cung cấp Rau Sạch Đà Lạt Mart (Rau củ tươi không thuế, dầu Oliu chịu thuế 8%)",
    supplierName: "Công ty TNHH Rau Sạch Đà Lạt Mart",
    data: {
      supplier_name: "Công ty TNHH Rau Sạch Đà Lạt Mart",
      supplier_tax_code: "0314892341",
      supplier_phone: "0908123456",
      supplier_address: "128 Đinh Tiên Hoàng, P.1, TP. Đà Lạt, Lâm Đồng",
      invoice_number: "HD-2026-0892",
      order_date: new Date().toISOString().slice(0, 10),
      items: [
        {
          raw_name: "Xà lách Romaine tươi Đà Lạt",
          quantity: 15,
          unit: "kg",
          unit_price: 32000,
          line_total: 480000,
          note: "Hàng loại 1 chọn lọc",
          tax_rate: 0,
          is_taxable: false,
        },
        {
          raw_name: "Chanh vàng không hạt",
          quantity: 10,
          unit: "kg",
          unit_price: 45000,
          line_total: 450000,
          note: "Tươi mọng nước",
          tax_rate: 0,
          is_taxable: false,
        },
        {
          raw_name: "Cà chua bi Cherry đỏ",
          quantity: 8,
          unit: "kg",
          unit_price: 38000,
          line_total: 304000,
          tax_rate: 0,
          is_taxable: false,
        },
        {
          raw_name: "Dầu Oliu Extra Virgin nguyên chất",
          quantity: 4,
          unit: "chai",
          unit_price: 185000,
          line_total: 740000,
          note: "Chai 1 lít",
          tax_rate: 8,
          is_taxable: true,
        },
      ],
      subtotal: 1974000,
      tax_percent: 0,
      tax_amount: 59200, // 740,000 * 8%
      total_amount: 2033200,
      confidence_score: 0.98,
    },
  },
  {
    id: "nguyen-lieu-pha-che",
    name: "Hóa đơn Nguyên Liệu Pha Chế & Sữa",
    description: "Công ty Cung ứng Nguyên liệu Tân Nhất Hương (Trà Oolong, Sữa tươi, Kem béo...)",
    supplierName: "Công ty CP Cung Ứng Nguyên Liệu Tân Nhất Hương",
    data: {
      supplier_name: "Công ty CP Cung Ứng Nguyên Liệu Tân Nhất Hương",
      supplier_tax_code: "0102983741",
      supplier_phone: "02838991234",
      supplier_address: "61A Trần Quang Diệu, P.13, Q.3, TP.HCM",
      invoice_number: "TNH-88219",
      order_date: new Date().toISOString().slice(0, 10),
      items: [
        {
          raw_name: "Trà Ô Long Kim Tuyên hảo hạng",
          quantity: 10,
          unit: "gói",
          unit_price: 125000,
          line_total: 1250000,
          note: "Gói 500g",
          tax_rate: 0,
          is_taxable: false,
        },
        {
          raw_name: "Sữa tươi thanh trùng Dalat Milk không đường",
          quantity: 24,
          unit: "hộp",
          unit_price: 34000,
          line_total: 816000,
          note: "Hộp 950ml",
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Kem béo thực vật Rich's Non-Dairy Creamer",
          quantity: 12,
          unit: "hộp",
          unit_price: 28500,
          line_total: 342000,
          note: "Hộp 454g",
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Đường cát trắng Biên Hòa Pure",
          quantity: 20,
          unit: "kg",
          unit_price: 22000,
          line_total: 440000,
          tax_rate: 8,
          is_taxable: true,
        },
      ],
      subtotal: 2848000,
      tax_percent: 0,
      tax_amount: 127840, // (816000+342000+440000)*8% = 1598000*8% = 127840
      total_amount: 2975840,
      confidence_score: 0.97,
    },
  },
  {
    id: "thit-hai-san",
    name: "Hóa đơn Thực Phẩm Thịt Bò & Hải Sản Tươi Sống",
    description: "Đại lý Thực phẩm Sạch Phúc Thịnh (Thịt bò thăn, Ức gà phi lê, Tôm sú - KCT)",
    supplierName: "Đại lý Thực Phẩm Sạch Phúc Thịnh",
    data: {
      supplier_name: "Đại lý Thực Phẩm Sạch Phúc Thịnh",
      supplier_tax_code: "0309981245",
      supplier_phone: "0918889922",
      supplier_address: "Bình Điền, P.7, Q.8, TP.HCM",
      invoice_number: "PT-260901",
      order_date: new Date().toISOString().slice(0, 10),
      items: [
        {
          raw_name: "Thịt bò thăn mềm Úc",
          quantity: 12,
          unit: "kg",
          unit_price: 260000,
          line_total: 3120000,
          note: "Hàng mát bảo quản 2-4 độ C",
          tax_rate: 0,
          is_taxable: false,
        },
        {
          raw_name: "Ức gà phi lê CP tươi",
          quantity: 20,
          unit: "kg",
          unit_price: 75000,
          line_total: 1500000,
          tax_rate: 0,
          is_taxable: false,
        },
        {
          raw_name: "Tôm sú tươi sống size 20-25 con/kg",
          quantity: 5,
          unit: "kg",
          unit_price: 320000,
          line_total: 1600000,
          tax_rate: 0,
          is_taxable: false,
        },
      ],
      subtotal: 6220000,
      tax_percent: 0,
      tax_amount: 0,
      total_amount: 6220000,
      confidence_score: 0.96,
    },
  },
  {
    id: "simba-food",
    name: "Phiếu Giao Hàng SIM BA (Thuế Hỗn Hợp + Món Gạch Bỏ)",
    description: "Công ty CP Thương mại SIM BA (Đậu nành, trứng cá, rong biển 8% VAT, trứng gà 0% VAT, kèm 2 món gạch bỏ)",
    supplierName: "Công ty Cổ phần Thương mại SIM BA",
    data: {
      supplier_name: "Công ty Cổ phần Thương mại SIM BA",
      supplier_tax_code: "0303123890",
      supplier_phone: "0354010285",
      supplier_address: "968 Ba Tháng Hai, P. Phú Thọ, TP. Hồ Chí Minh / Kho SG_K032 Bạch Đằng, P. Hồng Hà, Hà Nội",
      invoice_number: "26413820",
      order_date: "2026-09-04",
      items: [
        {
          raw_name: "Trứng gà tươi (30 quả/khay)",
          quantity: 1,
          unit: "Khay",
          unit_price: 84000,
          line_total: 84000,
          tax_rate: 0,
          is_taxable: false,
        },
        {
          raw_name: "Đậu nành luộc đông lạnh Edamame 400g",
          quantity: 4,
          unit: "Gói",
          unit_price: 34500,
          line_total: 138000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Trứng cá chế biến đông lạnh Tobiko Orange 500g",
          quantity: 1,
          unit: "Hộp",
          unit_price: 440000,
          line_total: 440000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Trứng cá tuyết chế biến Yamaya 500g",
          quantity: 1,
          unit: "Gói",
          unit_price: 280000,
          line_total: 280000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Mù tạt 505 Nama Wasabi Kaneku",
          quantity: 2,
          unit: "Gói",
          unit_price: 300000,
          line_total: 600000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Rong biển đỏ ướp muối 500g",
          quantity: 1,
          unit: "Gói",
          unit_price: 230000,
          line_total: 230000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Rong biển xanh ướp muối 500g",
          quantity: 1,
          unit: "Gói",
          unit_price: 230000,
          line_total: 230000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Trứng gà Ise - Vfood Vitamin E (hộp 10 quả)",
          quantity: 1,
          unit: "Hộp",
          unit_price: 48000,
          line_total: 48000,
          tax_rate: 0,
          is_taxable: false,
        },
        {
          raw_name: "Gừng chế biến Menyo Sushigari Pink 1.5Kg",
          quantity: 2,
          unit: "Gói",
          unit_price: 85000,
          line_total: 170000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Cá trứng đông lạnh Frozen Capelin Shisamo",
          quantity: 2,
          unit: "Khay",
          unit_price: 70000,
          line_total: 140000,
          tax_rate: 0,
          is_taxable: false,
        },
        {
          raw_name: "Bột khoai tây KATAKURIKO",
          quantity: 1,
          unit: "Túi",
          unit_price: 35000,
          line_total: 35000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Hạt bạch quả đông lạnh FROZEN GINKGO (KARATSUKI GINNAN)",
          quantity: 1,
          unit: "Túi",
          unit_price: 415000,
          line_total: 415000,
          tax_rate: 0,
          is_taxable: false,
          note: "Có nét gạch trên hóa đơn",
        },
        {
          raw_name: "Vây cá đuối 250g",
          quantity: 1,
          unit: "Gói",
          unit_price: 145000,
          line_total: 145000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Vỏ tắc Nhật: Kizami Yuzu (Khô) 250g",
          quantity: 1,
          unit: "Gói",
          unit_price: 165000,
          line_total: 165000,
          tax_rate: 0,
          is_taxable: false,
          note: "Có nét gạch trên hóa đơn",
        },
        {
          raw_name: "Rong biển nướng cắt sợi Kizami Nori",
          quantity: 1,
          unit: "Túi",
          unit_price: 115000,
          line_total: 115000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Nước tương Higashimaru Usukuchi Shoyu 1.8L",
          quantity: 1,
          unit: "Chai",
          unit_price: 170000,
          line_total: 170000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Súp Soba Tsuyu Sauce (Somi Shokuhin) 1.8L",
          quantity: 1,
          unit: "Chai",
          unit_price: 340000,
          line_total: 340000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Xốt Yakiniku No Tare Deluxe (Somi Shokuhin) 2 kg",
          quantity: 1,
          unit: "Hộp",
          unit_price: 345000,
          line_total: 345000,
          tax_rate: 8,
          is_taxable: true,
        },
        {
          raw_name: "Nước xốt Yakiniku sauce 2kg",
          quantity: 1,
          unit: "Chai",
          unit_price: 640000,
          line_total: 640000,
          tax_rate: 8,
          is_taxable: true,
        },
      ],
      excluded_items: [
        "Hạt bạch quả đông lạnh FROZEN GINKGO (KARATSUKI GINNAN)",
        "Vỏ tắc Nhật: Kizami Yuzu (Khô) 250g",
      ],
      subtotal: 4730000,
      tax_percent: 8,
      tax_amount: 310240,
      total_amount: 5040240,
      confidence_score: 0.99,
    },
  },
];
